# Generated by Django 6.0.2 on 2026-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Contact email", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Vendor's website or social media profile",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="vendors/"),
        ),
    ]
