# Generated by Django 6.0.2 on 2026-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vendorprofile_email_vendorprofile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food & Beverages", "Food & Beverages"),
                    ("Fashion & Tailoring", "Fashion & Tailoring"),
                    ("Agriculture & Produce", "Agriculture & Produce"),
                    ("Handicrafts & Art", "Handicrafts & Art"),
                    ("Electronics & Repair", "Electronics & Repair"),
                    ("Beauty & Wellness", "Beauty & Wellness"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
